version: '3.8'

services:
  web:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    restart: always
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  db-data:
