version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.2.0
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: password
      MONGODB_DATABASE: mydatabase

  ui:
    build: ./ui
    container_name: ui
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - kafka
      - mongodb
