version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - bddata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64  # Specify the platform for phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 6033

volumes:
  bddata:
